# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cpacket.proto\x12\x0cProtoMessage"\xac\x01\n\x0cPacketHeader\x12\x0e\n\x06obj_id\x18\x01 \x02(\t\x12\x0e\n\x03ver\x18\x02 \x01(\r:\x01\x30\x12\x11\n\ttick_freq\x18\x03 \x02(\x04\x12<\n\nid_strings\x18\x04 \x03(\x0b\x32(.ProtoMessage.PacketHeader.IdStringEntry\x1a+\n\rIdStringEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t"j\n\x06Packet\x12\x0c\n\x04tick\x18\x01 \x02(\x04\x12\x0b\n\x03\x63md\x18\x02 \x02(\r\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x02(\x04\x12\x0c\n\x04size\x18\x04 \x02(\r\x12\r\n\x05\x66lags\x18\x05 \x01(\r\x12\x0e\n\x06pkt_id\x18\x06 \x01(\x04\x12\n\n\x02pc\x18\x07 \x01(\x04'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "packet_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PACKETHEADER._serialized_start = 31
    _PACKETHEADER._serialized_end = 203
    _PACKETHEADER_IDSTRINGENTRY._serialized_start = 160
    _PACKETHEADER_IDSTRINGENTRY._serialized_end = 203
    _PACKET._serialized_start = 205
    _PACKET._serialized_end = 311
# @@protoc_insertion_point(module_scope)
